Update README.md with my github link and brief description
Code-the-Dream-School/ee-prac-team2-front pull request #15
Opened 2023-11-06 04:35 UTC by anniethewebcoder

2023-11-07 20:36 UTC, dargaCode requested changes
Thanks Annie! Just need to fix up the parentheses and small typo and you'll be good to go!

2023-11-07 20:36 UTC, dargaCode commented on README.md
> +- **Annie** ([@anniethewebcoder](https://github.com/anniethewebcoder) is a studying React and Ruby on Rails at Code the Dream.
Looking good, just a small typo fix:

```suggestion
- **Annie** ([@anniethewebcoder](https://github.com/anniethewebcoder)) is studying React and Ruby on Rails at Code the Dream.
```

2023-11-07 22:20 UTC, anniethewebcoder commented on README.md
> +- **Annie** ([@anniethewebcoder](https://github.com/anniethewebcoder) is a studying React and Ruby on Rails at Code the Dream.
Got it, thanks!

2023-11-07 22:23 UTC, anniethewebcoder commented
I fixed a grammatical error as per Darga's suggestion.

2023-11-08 00:15 UTC, dargaCode requested changes
One more small fix please =D

2023-11-08 00:15 UTC, dargaCode commented on README.md
> +- **Annie** ([@anniethewebcoder](https://github.com/anniethewebcoder) is studying React and Ruby on Rails at Code the Dream.
Sorry you're still missing the extra closing perenthesis after your usename!

```suggestion
- **Annie** ([@anniethewebcoder](https://github.com/anniethewebcoder)) is studying React and Ruby on Rails at Code the Dream.
```

2023-11-10 07:24 UTC, anniethewebcoder commented
I added ")"

2023-11-12 01:58 UTC, dargaCode approved these changes
Great!

2023-11-12 01:59 UTC, merged