#16 activities list view -Victoria
Code-the-Dream-School/ee-prac-team2-front pull request #22
Opened 2023-11-12 20:39 UTC by Victoria240

Solves Issue #16

2023-11-13 16:57 UTC, angelkbrown approved these changes
Nice work, Victoria! 🎉 I'll defer to Darga for any more advice on implementation details, especially around the typescript options. But I ran your branch locally and it worked great for me! 👍

2023-11-13 16:57 UTC, angelkbrown commented on src/ActivityList.tsx
> +export default ActivityList;
Nice!! Good job figuring out how to define an interface, functional component AND a list of Activities with typescript! 👏

2023-11-13 16:57 UTC, angelkbrown commented on src/App.tsx
> +// }
Don't be afraid to delete! That's what's good about version control -- we can always look at past versions if we need to add something back in.

2023-11-15 04:25 UTC, dargaCode requested changes
Great job Victoria! 

Sorry there were a couple of details here that I forgot to add to the ticket. Please make these changes and then when you've re-pushed, you can "re-request review" from me next to my name in the upper right of the page 🙏

2023-11-15 04:25 UTC, dargaCode commented on src/ActivityList.tsx
> +export default ActivityList;
Yes well done!

2023-11-15 04:25 UTC, dargaCode commented on src/main.tsx
> +
You should only have to add these comments to your own new files - I think it should be safe to revert this file?

2023-11-15 04:25 UTC, dargaCode commented on src/ActivityList.tsx
> +  const activitiesData: Activity[] = [
Eventually we're going to need this component to accept props. Can you please move this activities array out to App and then pass it into `ActivitiesList` as a prop called `activities`?

(In order to still give this array your custom type, you'll have to export `Activity` from here as a non-default export, and then import into `App` along with the `ActivitiesList`:

`import ActivitiesList, { Activity } from "./components/ActivitiesList/ActivitiesList"`
)

2023-11-15 04:25 UTC, dargaCode commented on src/ActivityList.tsx
> +interface Activity {
yessss 💪

2023-11-15 04:25 UTC, dargaCode commented on src/ActivityList.tsx
Please rename this component and file to `ActivitiesList` and move the file into a new folder called `src/components/ActivitiesList`

Sorry I forgot to mention this in the ticket!

2023-11-15 04:25 UTC, dargaCode commented on src/App.tsx
> -      <HelloWorld msg="Hello EE Practicum Team 2!" />
For now please leave the old code in App as well, and add ActivitiesList to the render right below HelloWorld

(We can come back later on and remove these other components)

2023-11-15 04:25 UTC, dargaCode commented on src/App.tsx
> +import ActivityList from "./ActivityList.js";
I know you said the import isn't working correctly. After you move the `ActivityList` to the new folder inside `/components`, please try following the same format as the examples on lines 2-3. 

We're using the `@` shortcuts to make it easier to import from important folders without ever having to use `../../../` to go up to parent folders. 

You can also see here that the import for this project expects the file extensions to be left off entirely:

```suggestion
import ActivityList, { Activity } from "@components/ActivityList/ActivityList";
```

2023-11-15 22:48 UTC, dargaCode approved these changes
Awesome thank you! Approved =D

Please don't merge yet though - In the team meeting we can discuss  blending together aspects of these 3 different PRs

2023-11-16 23:36 UTC, merged